### ISSUE TITLE
URL is not working

### ISSUE THREAD

**Issue by cetincakiroglu** [Ideaviate/html5-css3-js-calculator#8]
Demo url is not working anymore

**Comment by wanderling** [comment]
To be clear. The demo link now goes to a sketchy "Clean my PC" website. Reporting this FYI.

**Comment by c-eliasson** [comment]
@wanderling Thanks for the heads up! The company that hosted the demo closed shop many years ago, and apparently the domain has been taken over by scammers 😠

Removed the demo link from the readme, just in case someone finds this old project.
